<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title><?php print $page_title ?? 'CSV Uploader'; ?></title>
    <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    <link href="/styles/style.css" rel="stylesheet" media="all" />
</head>
    <body>
        <header class="main">
            CSV Uploader
            <nav class="main">
                <a href="/" class="active">Home</a>
                <a href="/people">People</a>
                <a href="/groups">Groups</a>
            </nav>
        </header>
        <main>
            <?php
                $layout = $data['layout'] ?? 'index';
                include $layout.'.phtml';
            ?>
        </main>
    </body>
</html>