<div id="message"></div>
<form enctype="multipart/form-data">
    <label for="csv-file">
        Choose File:
        <input type="file" name="csv-file" id="csv-file" class="file-input" required aria-required="true" />
    </label>
    <label for="csv-type">
        Choose Type:
        <select name="csv-type" id="csv-type" required>
            <option value="person">People</option>
            <option value="people_group">Groups</option>
        </select>
    </label>
    <a class="btn" id="upload-btn">Upload</a>
</form>